### PR TITLE
python program for adding the images

### PR DESCRIPTION
**Pull request by u22668323**
The python program for adding the images

### CODE REVIEW

**Review by johnpeterprogramming — CHANGES_REQUESTED** [review]
Hey, looks good. But it's a bit dangerous to include your database and api secrets in the code. Could you just replace them with "(apikey)" and "(password)" for example. Also please make a folder called scripts

**Comment by u22668323** [comment]
ok will do

**Review by johnpeterprogramming — CHANGES_REQUESTED** [review]
The api key is still there xD

**Comment by u22668323** [comment]
yeah i just saw but i fixed it now

**Comment by u22668323** [comment]
I also dont see how to make a folder for this

**Comment by johnpeterprogramming** [comment]
> I also dont see how to make a folder for this

It's ok I'll do it

**Review by johnpeterprogramming — APPROVED** [review]

**Pull request merged**
